version: "3.9"

volumes:
  backend-data:
  backend-go-data:

services:
  web:
    container_name: damagecontrol_app
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8000:80"

  backend:
    container_name: damagecontrol_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - backend-data:/pb_data
      - backend-go-data:/go
      - ./backend:/app

  frontend:
    container_name: damagecontrol_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/app/app

  frontend-test:
    container_name: damagecontrol_frontend_test
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run test:ui
    entrypoint: ""
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/usr/app/app
